description: ""
intro: "The uMod database extensions implement a generalized database abstraction layer for both MySQL and SQLite."

topics:
  - title: "Open a connection"
    summary: "Create a new connection to a database by providing the database file location or an address (URI & port), a database name, and authentication credentials."
  - title: "Close the connection"
    summary: "Close an existing connection to the database."
  - title: "Query the database"
    summary: "Retrieve data from the database, typically using a SELECT statement."
  - title: "Insert query"
    summary: "Insert records into the database using an INSERT statement."
  - title: "Update query"
    summary: "Update existing records in the database using an UPDATE statement."
  - title: "Delete query"
    summary: "Delete existing records from a database using a DELETE statement."
  - title: "Non-query"
    summary: "By definition a non-query is a query which modifies data and does not retrieve data.  Insert, Update, and Delete queries are all considered non-queries."
